version: 2.0

jobs:
    build:
        docker:
            - image: cibuilds/hugo:latest
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  - ""
            - run:
                name: Prepare shell commands
                command: chmod +x .circleci/deploy.sh
            - deploy:
                name: Deploy to Github Pages
                command: ./.circleci/deploy.sh
